# # Tetrodotoxin
# Copyright (c) 2023-present Matt Kaes and contributors

"""Canonical multi-Scene TTX application sources."""

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sources",
    srcs = [
        "main.ttx",
        "package.ttx",
        "resources/icon.png",
        "resources/logo.png",
        "scenes/splash.ttx",
        "scenes/title.ttx",
    ],
)
