// Perimortem Engine
// Copyright © Matt Kaes

#include "tetrodotoxin/compiler/compiler.hpp"

#include "perimortem/core/data.hpp"

#include "perimortem/utility/null_terminated.hpp"

#include "tetrodotoxin/compiler/assembler/x86_64.hpp"
#include "tetrodotoxin/linker/linker.hpp"
#include "tetrodotoxin/linker/target/elf.hpp"

using namespace Perimortem;
using namespace Perimortem::Core;
using namespace Perimortem::Memory;
using namespace Tetrodotoxin::Compiler;

auto Compiler::generate_c_header() -> Dynamic::Bytes {
  Dynamic::Bytes header;
  header.concat("// Generated by Tetrodotoxin\n"_view);
  header.concat("#pragma once\n\n"_view);
  header.concat("#include \"perimortem/core/view/bytes.hpp\"\n"_view);

  for (Count i = 0; i < functions.get_size(); i++) {
    auto func = functions[i];
    header.concat(func.result.name);
    header.append(' ');
    header.concat(func.name);
    header.append('(');

    for (Count a = 0; a < func.args.get_size(); a++) {
      auto arg = func.args[a];
      if (a > 0) {
        header.append(',');
      }
      header.concat(arg.type.name);
      header.append(' ');
      header.concat(arg.name);
    }

    header.concat(");\n"_view);
  }

  return header;
}

auto Compiler::compile_function(
    Perimortem::Core::View::Bytes module,
    Perimortem::Core::View::Bytes name,
    Intermediate::Type return_type,
    Perimortem::Core::View::Vector<Intermediate::Argument> arguments) -> Count {
  // Create the canonical name for the function.
  Context::Function func;
  func.name = names.canonicalize(module, name);
  func.args = arguments;
  func.symbol = symbols.get_size();

  // Capture the start of the range.
  const auto func_start = machine_code.get_size();

  // Create the initial symbol
  auto symbol = Context::Symbol::create_func(
      func.name, Context::Symbol::Visability::Global);
  symbols.insert(symbol);
  sym_table[func.name] = func.symbol;

  //========================================================
  //         Perform an actual mock compile.
  //========================================================
  Assembler::x86_64 assembler(machine_code);
  assembler.prologue(arguments);
  assembler.push(Assembler::x86_64::Reg::RBX);
  assembler.push(Assembler::x86_64::Reg::R12);
  // Store args
  assembler.mov(Assembler::x86_64::Reg::RDI, Assembler::x86_64::Reg::RBX);
  assembler.mov(Assembler::x86_64::Reg::RSI, Assembler::x86_64::Reg::R12);
  // Load print call for the first time.
  assembler.read_only(Assembler::x86_64::Reg::RDI);
  load_string(assembler, Assembler::x86_64::Reg::RDI, "Compiler Test"_view);
  assembler.mov("Compiler Test"_view.get_size(), Assembler::x86_64::Reg::RSI);
  call_extern(assembler, "print"_view);
  // Restore args and call print second time.
  assembler.mov(Assembler::x86_64::Reg::RBX, Assembler::x86_64::Reg::RDI);
  assembler.mov(Assembler::x86_64::Reg::R12, Assembler::x86_64::Reg::RSI);
  call_extern(assembler, "print"_view);
  // Restore reg and return.
  assembler.pop(Assembler::x86_64::Reg::R12);
  assembler.pop(Assembler::x86_64::Reg::RBX);
  assembler.epilogue(return_type);
  //========================================================
  //               End mock compile.
  //========================================================

  // Fix up the end range of the function.
  symbols[func.symbol].set_range(
      {func_start, machine_code.get_size() - func_start});
}

auto Compiler::load_string(
    Assembler::x86_64 assembler,
    Assembler::x86_64::Reg dst,
    Perimortem::Core::View::Bytes string) -> void {
  auto ref_index = ref_string(string);

  assembler.read_only(dst);
  relocs.insert(
      Context::Relocation::create_pc32(ref_index, machine_code.get_size()));
}

auto Compiler::call_extern(
    Assembler::x86_64 assembler,
    Perimortem::Core::View::Bytes function) -> void {
  auto ref_index = ref_extern(function, Context::Symbol::Type::Func);

  assembler.call();
  relocs.insert(
      Context::Relocation::create_pc32(ref_index, machine_code.get_size()));
}

auto Compiler::ref_local(Perimortem::Core::View::Bytes string_value) -> Count {
  auto symbol_index = sym_table.find_or_default(string_value, Count(-1));

  if (symbol_index == -1) {
    // TODO: Diagnostics
    __builtin_debugtrap();
  }
}

auto Compiler::ref_string(Perimortem::Core::View::Bytes string_value) -> Count {
  auto symbol_index = sym_table.find_or_default(string_value, Count(-1));
  if (symbol_index != -1) {
    return symbol_index;
  }

  // If the string isn't found then we can just add it to the read only data
  // string table lazily.
  symbol_index = symbols.get_size();
  auto range = strings.add_string(string_value, symbol_index);

  // We only need an arbitrary unique local name.
  auto name = names.make_local_unique();
  auto symbol = Context::Symbol::create_string(name, range);
  symbols.insert(symbol);

  return symbol_index;
}

auto Compiler::ref_extern(
    Perimortem::Core::View::Bytes name,
    Context::Symbol::Type type) -> Count {
  auto symbol_index = sym_table.find_or_default(name, Count(-1));
  if (symbol_index != -1) {
    return symbol_index;
  }

  // Add an external reference to the table.
  symbol_index = symbols.get_size();
  auto symbol = Context::Symbol::create_extrenal(name, type);
  symbols.insert(symbol);

  return symbol_index;
}
