// Perimortem Engine
// Copyright © Matt Kaes

#include "tetrodotoxin/compiler/compiler.hpp"

#include "perimortem/core/data.hpp"

#include "perimortem/utility/null_terminated.hpp"

using namespace Perimortem;
using namespace Perimortem::Core;
using namespace Perimortem::Memory;
using namespace Tetrodotoxin::Compiler;

auto Compiler::compile_function(
    View::Bytes module,
    View::Bytes name,
    Intermediate::Type return_type,
    View::Vector<Intermediate::Argument> arguments) -> Count {
  Assembler::x86_64 assembler(machine_code);

  const auto canon_name = names.canonicalize(module, name);
  const Count func_start = machine_code.get_size();

  // TODO: compile the actual function body from the TTX AST.
  assembler.prologue(arguments);
  assembler.push(Assembler::x86_64::Reg::RBX);
  assembler.push(Assembler::x86_64::Reg::R12);
  // Store args
  assembler.mov(Assembler::x86_64::Reg::RDI, Assembler::x86_64::Reg::RBX);
  assembler.mov(Assembler::x86_64::Reg::RSI, Assembler::x86_64::Reg::R12);
  // Load print call for the first time.
  load_string(assembler, Assembler::x86_64::Reg::RDI, "Compiler Test"_view);
  assembler.mov("Compiler Test"_view.get_size(), Assembler::x86_64::Reg::RSI);
  call_extern(assembler, "print"_view);
  // Restore args and call print second time.
  assembler.mov(Assembler::x86_64::Reg::RBX, Assembler::x86_64::Reg::RDI);
  assembler.mov(Assembler::x86_64::Reg::R12, Assembler::x86_64::Reg::RSI);
  call_extern(assembler, "print"_view);
  // Restore reg and return.
  assembler.pop(Assembler::x86_64::Reg::R12);
  assembler.pop(Assembler::x86_64::Reg::RBX);
  assembler.epilogue(return_type);

  const Count func_size = machine_code.get_size() - func_start;

  auto func_sym = Context::Symbol::create_func(
      canon_name, Context::Symbol::Visability::Global);
  func_sym.set_range({func_start, func_size});

  const Count sym_index = symbols.get_size();
  symbols.insert(func_sym);

  // Copy arguments into arena so the function entry remains valid after
  // the caller's stack frame is gone.
  auto* args_copy = reinterpret_cast<Intermediate::Argument*>(
      arena.allocate(sizeof(Intermediate::Argument) * arguments.get_size()));
  for (Count j = 0; j < arguments.get_size(); j++) {
    args_copy[j] = arguments.at(j);
  }

  functions.insert({
    canon_name,
    View::Vector<Intermediate::Argument>(args_copy, arguments.get_size()),
    return_type,
    sym_index,
  });

  return sym_index;
}

auto Compiler::generate_cpp_header(Dynamic::Bytes& out) -> void {
  out.concat(
      "//    This file is generated by the Tetrodotoxin compiler\n"_view);
  out.concat("//         Manual edits can break the C++/TTX ABI\n\n"_view);
  out.concat("#pragma once\n\n"_view);
  out.concat("#include \"perimortem/core/view/bytes.hpp\"\n\n"_view);

  // Extern C block to prevent name mangling.
  out.concat("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"_view);

  for (Count i = 0; i < functions.get_size(); i++) {
    const auto& func = functions.at(i);
    out.concat(func.result.name);
    out.concat(" "_view);
    out.concat(func.name);
    out.append('(');
    for (Count j = 0; j < func.args.get_size(); j++) {
      if (j > 0) {
        out.concat(", "_view);
      }
      out.concat(func.args.at(j).type.name);
      out.append(' ');
      out.concat(func.args.at(j).name);
    }
    out.concat(");\n"_view);
  }

  out.concat("\n#ifdef __cplusplus\n}\n#endif\n"_view);
}

auto Compiler::load_string(
    Assembler::x86_64& assembler,
    Assembler::x86_64::Reg dst,
    View::Bytes string) -> void {
  const Count sym_index = ref_string(string);
  assembler.read_only(dst);
  // read_only creates an LEA with a disp32 to be relocated
  relocs.insert(
      Context::Relocation::create_pc32(sym_index, machine_code.get_size()));
}

auto Compiler::call_extern(Assembler::x86_64& assembler, View::Bytes function)
    -> void {
  const Count sym_index = ref_extern(function, Context::Symbol::Type::Func);
  assembler.call();
  // call() creates a CALL with a disp32 to be replcated
  relocs.insert(
      Context::Relocation::create_pc32(sym_index, machine_code.get_size()));
}

auto Compiler::ref_extern(View::Bytes name, Context::Symbol::Type type)
    -> Count {
  for (Count i = 0; i < symbols.get_size(); i++) {
    if (symbols.at(i).get_context() == Context::Symbol::Location::External &&
        symbols.at(i).get_name() == name) {
      return i;
    }
  }
  const Count index = symbols.get_size();
  symbols.insert(Context::Symbol::create_extrenal(name, type));
  return index;
}

auto Compiler::ref_string(View::Bytes string_value) -> Count {
  for (Count i = 0; i < symbols.get_size(); i++) {
    const auto& sym = symbols.at(i);
    if (sym.get_context() != Context::Symbol::Location::Strings) {
      continue;
    }
    const auto range = sym.get_range();
    if (strings.get_view().slice(range.start, range.size) == string_value) {
      return i;
    }
  }
  const Count index = symbols.get_size();
  const auto range = strings.add_string(string_value, index);
  symbols.insert(
      Context::Symbol::create_string(names.make_local_unique(), range));
  return index;
}
