"""
Starlark rules for the Tetrodotoxin (TTX) language.

The TTX compiler aims to provide a way to compile TTX directly to binary files
which can be pulled in to the regular `cc_toolchain`.

`ttx_binary` supports the current application bridge: a Library package exports
an entry point, and generated C++ lowers the current splash-scene application
structs into direct Perimortem runtime calls.

Usage in a BUILD file:

    load("//tetrodotoxin:ttx.bzl", "ttx_library")

    ttx_library(
        name = "my_lib",
        srcs = ["png.ttx"],
    )

    ttx_binary(
        name = "my_app",
        srcs = ["main.ttx"],
        entry_module = "main",
        entry = "main",
        foreign_config_type = "TTX_main_SceneConfig",
        foreign_sprite_type = "TTX_Graphics_Sprite",
        foreign_symbol = "run_sprite_fade_scene",
        render_include = "ttx_generated/default_2d_shader.hpp",
        render_import_name = "Default2D",
        render_symbol = "default_2d_shader_renderer",
        render_deps = [":default_2d_shader"],
    )

A generated header is automatically available to dependents:

    #include "ttx_generated/my_lib.hpp"

For Render packages, the generated archive exports SPIR-V blobs and ABI metadata
derived from the TTX source. The generated header declares those symbols and
the host-side input struct.

For Library packages, the generated archive exports top-level TTX functions
through the current C-compatible host ABI. The supported lowering surface is
intentionally narrow today: `View[Bytes]` parameters, source `struct` objects
passed to `foreign` functions by pointer, `[]`/`Void` returns, and foreign-style
calls with literal-backed values. `ttx_binary` then provides the current app
runner lowering on top of that ABI.
"""

load("@rules_cc//cc:find_cc_toolchain.bzl", "CC_TOOLCHAIN_ATTRS", "find_cc_toolchain")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")

TtxPackageInfo = provider(
    doc = "Transitive TTX source files that must be visible during Tetrodotoxin resolution.",
    fields = {
        "source_files": "depset of .ttx source files used for package and raw-file resolution.",
    },
)

def _ttx_binary_bridge_impl(ctx):
    source = ctx.actions.declare_file(ctx.attr.name + ".cpp")
    ctx.actions.write(
        output = source,
        content = """//    This file is generated by the Tetrodotoxin Bazel rules
//         Manual edits can break the C++/TTX ABI

#include "perimortem/core/data.hpp"
#include "perimortem/core/diagnostics/log.hpp"
#include "perimortem/core/null_terminated.hpp"
#include "perimortem/core/static/bytes.hpp"
#include "perimortem/core/time.hpp"

#include "perimortem/system/file.hpp"
#include "perimortem/serialization/format/png.hpp"

#include "perimortem/graphics/image.hpp"
#include "perimortem/graphics/window.hpp"

#include "{program_include}"
#include "{render_include}"

namespace TtxApplicationBridge {{

auto resolve_sprite_renderer(Perimortem::Core::View::Bytes render_name)
    -> const Perimortem::Graphics::Render& {{
  if (render_name == "{render_import_name}"_view) {{
    return Ttx::{render_symbol};
  }}

  Perimortem::Core::Diagnostics::Log::fatal(
      "Unknown sprite render import."_view);
  return Ttx::{render_symbol};
}}

template <Count capacity>
auto copy_title_to_c_string(
    Perimortem::Core::Static::Bytes<capacity>& output,
    Perimortem::Core::View::Bytes source) -> const char* {{
  if (source.get_size() >= capacity) {{
    Perimortem::Core::Diagnostics::Log::fatal(
        "TTX application title is too large."_view);
  }}

  Perimortem::Core::Data::copy(
      output.get_data(), source.get_data(), source.get_size());
  output[source.get_size()] = '\\0';
  return reinterpret_cast<const char*>(output.get_data());
}}

auto calculate_scene_alpha(
    Real_64 elapsed_seconds,
    Real_64 fade_in_seconds,
    Real_64 hold_seconds,
    Real_64 fade_out_seconds) -> Real_32 {{
  if (elapsed_seconds < fade_in_seconds) {{
    return Real_32(elapsed_seconds / fade_in_seconds);
  }}

  if (elapsed_seconds < fade_in_seconds + hold_seconds) {{
    return 1.0f;
  }}

  return Real_32(
      1.0 - (elapsed_seconds - fade_in_seconds - hold_seconds) /
                fade_out_seconds);
}}

auto load_sprite_image(Perimortem::Core::View::Bytes image_path)
    -> Perimortem::Graphics::Image {{
  Perimortem::System::File image_file;
  if (!image_file.read(image_path)) {{
    Perimortem::Core::Diagnostics::Log::fatal(
        "TTX application failed to load image."_view);
  }}

  Perimortem::Graphics::Image image =
      Perimortem::Serialization::Format::Png::decode(image_file.get_view());
  if (image.get_width() == 0 || image.get_height() == 0) {{
    Perimortem::Core::Diagnostics::Log::fatal(
        "TTX application image decode failed."_view);
  }}

  return image;
}}

auto create_sprite(
    const Ttx::{foreign_sprite_type}* sprite,
    const Perimortem::Graphics::Image& image)
    -> Perimortem::Graphics::Sprite2D& {{
  const Perimortem::Graphics::Render& renderer =
      resolve_sprite_renderer(sprite->renderer.name);
  if (!renderer.is_valid()) {{
    Perimortem::Core::Diagnostics::Log::fatal(
        "TTX application renderer is invalid."_view);
  }}

  Perimortem::Graphics::Sprite2D& scene_sprite =
      Perimortem::Graphics::Sprite2D::create(image);
  scene_sprite.set_renderer(renderer);
  scene_sprite.set_size_pixels(
      sprite->size_pixels.width, sprite->size_pixels.height);
  scene_sprite.set_position(sprite->position_x, sprite->position_y);
  return scene_sprite;
}}

auto run_sprite_fade_scene(
    const Ttx::{foreign_config_type}* scene,
    const Ttx::{foreign_sprite_type}* top_icon,
    const Ttx::{foreign_sprite_type}* bottom_icon) -> void {{
  Perimortem::Core::Static::Bytes<128> title_buffer;
  const char* title = copy_title_to_c_string(title_buffer, scene->title);

  const Perimortem::Graphics::Image top_icon_image =
      load_sprite_image(top_icon->image);
  const Perimortem::Graphics::Image bottom_icon_image =
      load_sprite_image(bottom_icon->image);

  Perimortem::Graphics::Window window(
      scene->window_size, scene->window_size, title);
  Perimortem::Graphics::Scene graphics_scene(window);

  Perimortem::Graphics::Sprite2D& top_sprite =
      create_sprite(top_icon, top_icon_image);
  Perimortem::Graphics::Sprite2D& bottom_sprite =
      create_sprite(bottom_icon, bottom_icon_image);

  const Real_64 total_seconds =
      scene->fade_in_seconds + scene->hold_seconds + scene->fade_out_seconds;
  const Perimortem::Core::Time start_time = Perimortem::Core::Time::now();

  while (graphics_scene.poll_events()) {{
    const Real_64 elapsed_seconds =
        start_time.measure().convert_to_seconds();
    if (elapsed_seconds >= total_seconds) {{
      break;
    }}

    const Real_32 alpha = calculate_scene_alpha(
        elapsed_seconds, scene->fade_in_seconds, scene->hold_seconds,
        scene->fade_out_seconds);
    top_sprite.set_alpha(alpha);
    bottom_sprite.set_alpha(alpha);
    graphics_scene.render();
  }}

  graphics_scene.wait_idle();
}}

}}  // namespace TtxApplicationBridge

extern "C" void {foreign_symbol}(
    const Ttx::{foreign_config_type}* scene,
    const Ttx::{foreign_sprite_type}* top_icon,
    const Ttx::{foreign_sprite_type}* bottom_icon) {{
  TtxApplicationBridge::run_sprite_fade_scene(scene, top_icon, bottom_icon);
}}

int main() {{
  Ttx::{entry_symbol}();
  return 0;
}}
""".format(
            entry_symbol = ctx.attr.entry_symbol,
            foreign_config_type = ctx.attr.foreign_config_type,
            foreign_sprite_type = ctx.attr.foreign_sprite_type,
            foreign_symbol = ctx.attr.foreign_symbol,
            program_include = ctx.attr.program_include,
            render_include = ctx.attr.render_include,
            render_import_name = ctx.attr.render_import_name,
            render_symbol = ctx.attr.render_symbol,
        ),
    )
    return DefaultInfo(files = depset([source]))

_ttx_binary_bridge = rule(
    implementation = _ttx_binary_bridge_impl,
    attrs = {
        "entry_symbol": attr.string(mandatory = True),
        "foreign_config_type": attr.string(mandatory = True),
        "foreign_sprite_type": attr.string(mandatory = True),
        "foreign_symbol": attr.string(mandatory = True),
        "program_include": attr.string(mandatory = True),
        "render_include": attr.string(mandatory = True),
        "render_import_name": attr.string(mandatory = True),
        "render_symbol": attr.string(mandatory = True),
    },
)

def _canonical_ttx_symbol(module, name):
    return "TTX_" + module + "_" + name

def _collect_ttx_source_files(deps):
    return depset(transitive = [
        dep[TtxPackageInfo].source_files
        for dep in deps
    ])

def _ttx_library_impl(ctx):
    archive = ctx.actions.declare_file(ctx.attr.name + ".a")
    header = ctx.actions.declare_file("ttx_generated/" + ctx.attr.name + ".hpp")
    include_root = ctx.bin_dir.path
    if ctx.label.package:
        include_root = include_root + "/" + ctx.label.package

    args = ["--output", archive.path, "--header", header.path]
    dependency_source_files = _collect_ttx_source_files(ctx.attr.deps)
    for dep_source in dependency_source_files.to_list():
        args.extend(["--dep", dep_source.path])

    for src in ctx.files.srcs:
        args.append(src.path)

    ctx.actions.run(
        inputs = depset(
            direct = ctx.files.srcs,
            transitive = [dependency_source_files],
        ),
        outputs = [archive, header],
        executable = ctx.executable._compiler,
        arguments = args,
        mnemonic = "TtxCompile",
        progress_message = "Compiling TTX library %s" % ctx.label,
    )

    # Wrap the generated archive in CcInfo so cc_binary can depend on this
    # target without any extra boilerplate.
    cc_toolchain = find_cc_toolchain(ctx)
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )

    lib = cc_common.create_library_to_link(
        actions = ctx.actions,
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        static_library = archive,
    )

    linking_context = cc_common.create_linking_context(
        linker_inputs = depset([
            cc_common.create_linker_input(
                owner = ctx.label,
                libraries = depset([lib]),
            ),
        ]),
    )

    # Make the generated header available so consumers can write:
    #include "ttx_generated/<name>.hpp"
    compilation_context = cc_common.create_compilation_context(
        headers = depset([header]),
        system_includes = depset([include_root]),
    )

    return [
        CcInfo(
            compilation_context = compilation_context,
            linking_context = linking_context,
        ),
        TtxPackageInfo(
            source_files = depset(
                direct = ctx.files.srcs,
                transitive = [dependency_source_files],
            ),
        ),
        DefaultInfo(files = depset([archive, header])),
    ]

ttx_library = rule(
    implementation = _ttx_library_impl,
    attrs = dict(
        CC_TOOLCHAIN_ATTRS,
        srcs = attr.label_list(
            allow_files = [".ttx"],
            doc = "TTX source files compiled into the library.",
        ),
        deps = attr.label_list(
            providers = [TtxPackageInfo],
            doc = "TTX package dependencies whose source manifests must be visible during resolution.",
        ),
        _compiler = attr.label(
            default = "//tetrodotoxin:ttx",
            executable = True,
            cfg = "exec",
            doc = "The Tetrodotoxin compiler binary.",
        ),
    ),
    toolchains = ["@bazel_tools//tools/cpp:toolchain_type"],
    fragments = ["cpp"],
    doc = "Compiles TTX source files into an x86-64 ELF static library usable by cc_binary.",
)

ttx_package = rule(
    implementation = _ttx_library_impl,
    attrs = dict(
        CC_TOOLCHAIN_ATTRS,
        srcs = attr.label_list(
            allow_files = [".ttx"],
            doc = "Package manifest and owned TTX source files for this module.",
        ),
        deps = attr.label_list(
            providers = [TtxPackageInfo],
            doc = "Dependent TTX packages whose source manifests must be visible while resolving this module.",
        ),
        _compiler = attr.label(
            default = "//tetrodotoxin:ttx",
            executable = True,
            cfg = "exec",
            doc = "The Tetrodotoxin compiler binary.",
        ),
    ),
    toolchains = ["@bazel_tools//tools/cpp:toolchain_type"],
    fragments = ["cpp"],
    doc = "Compiles an authored TTX module rooted by dialect : Package; and exports its manifest to dependent TTX targets.",
)

def ttx_binary(
        name,
        srcs,
        entry_module,
        entry,
        foreign_config_type,
        foreign_sprite_type,
        foreign_symbol,
        render_include,
        render_import_name,
        render_symbol,
        render_deps,
        ttx_deps = [],
        deps = [],
        visibility = None):
    program_name = name + "_ttx"
    bridge_name = name + "_bridge"

    ttx_library(
        name = program_name,
        srcs = srcs,
        deps = ttx_deps,
    )

    _ttx_binary_bridge(
        name = bridge_name,
        entry_symbol = _canonical_ttx_symbol(entry_module, entry),
        foreign_config_type = foreign_config_type,
        foreign_sprite_type = foreign_sprite_type,
        foreign_symbol = foreign_symbol,
        program_include = "ttx_generated/" + program_name + ".hpp",
        render_include = render_include,
        render_import_name = render_import_name,
        render_symbol = render_symbol,
    )

    cc_binary(
        name = name,
        srcs = [":" + bridge_name],
        deps = [
            ":" + program_name,
            "//perimortem:graphics",
            "//perimortem:serialization",
            "//perimortem:system",
        ] + render_deps + ttx_deps + deps,
        visibility = visibility,
    )
