"""Canonical Echo TTX application sources."""

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sources",
    srcs = [
        "app.ttx",
        "main.ttx",
        "package.ttx",
    ],
)
