# """
# Stable ABI identities and machine lowering facts for Tetrodotoxin.
# """

# load("@rules_cc//cc:cc_library.bzl", "cc_library")

# package(default_visibility = ["//visibility:public"])

# cc_library(
#     name = "abi",
#     srcs = [
#         "export.cpp",
#         "linkage.cpp",
#         "symbol.cpp",
#         "type.cpp",
#     ],
#     hdrs = [
#         "export.hpp",
#         "linkage.hpp",
#         "symbol.hpp",
#         "type.hpp",
#     ],
#     include_prefix = "tetrodotoxin/abi",
#     strip_include_prefix = ".",
#     deps = [
#         "//perimortem:core",
#         "//perimortem:memory",
#         "//ttx:model",
#     ],
# )
