# # Tetrodotoxin
# Copyright (c) 2023-present Matt Kaes and contributors

"""Puffer SDK assembly metadata."""

filegroup(
    name = "providers",
    srcs = ["providers.manifest"],
    visibility = ["//visibility:public"],
)
