"""TTX demo sources for Perimortem."""

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "package",
    srcs = ["package.ttx"],
)

filegroup(
    name = "sources",
    srcs = glob(["*.ttx"]),
)

filegroup(
    name = "main",
    srcs = ["main.ttx"],
)

filegroup(
    name = "splash_screen",
    srcs = ["splash_screen.ttx"],
)
